apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove-old-files
      image: alpine:3.20
      script: |
        #!/bin/sh
        set -eu
        find /workspace/source \
          -mindepth 1 -maxdepth 1 \
          -exec rm -rf {} +

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test
spec:
  workspaces:
    - name: source
  steps:
    - name: lint-and-test
      image: python:3.10
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        set -eu
        pip install flake8 nose
        flake8 . --count \
          --select=E9,F63,F7,F82 \
          --show-source --statistics
        nosetests
